"use client";

import { useState } from "react";
import { useNotify } from "@/components/notification-banner";
import { StatusBadge } from "@/components/status-badge";
import {
  Button,
  Field,
  Input,
  tableClass,
  tdClass,
  thClass,
  theadClass,
  trClass,
} from "@/components/ui/primitives";
import { api, errorMessage } from "@/lib/api-client";
import { track } from "@/lib/analytics";
import { formatDateTime } from "./format";
import { AdminSection, TableScroll } from "./section";
import type { ComplianceNurse, ComplianceReport } from "./types";

const COLUMNS = ["Nurse", "License #", "License expiry", "TB screening expiry", "Eligible today"];

/** Quote every cell; neutralize leading =,+,-,@ so spreadsheets don't evaluate them. */
function csvCell(value: string): string {
  const safe = /^[=+\-@\t\r]/.test(value) ? `'${value}` : value;
  return `"${safe.replace(/"/g, '""')}"`;
}

function toCsv(report: ComplianceReport): string {
  const header = [
    "Name",
    "License number",
    "License expiry",
    "License status",
    "TB screening expiry",
    "TB status",
    "Eligible today",
  ];
  const lines = report.nurses.map((n) =>
    [
      n.name,
      n.licenseNumber ?? "",
      n.licenseExpiresAt ?? "",
      n.licenseStatus,
      n.tbScreeningExpiresAt ?? "",
      n.tbStatus,
      n.eligibleToday ? "yes" : "no",
    ]
      .map(csvCell)
      .join(","),
  );
  const stamp = [
    `Generated by: ${report.generatedBy}`,
    `Generated at: ${report.generatedAt}`,
    `Reason: ${report.reason}`,
  ].map((s) => csvCell(s));
  return [...stamp, "", header.map(csvCell).join(","), ...lines].join("\r\n");
}

function downloadCsv(report: ComplianceReport) {
  const blob = new Blob([toCsv(report)], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `compliance-report-${report.generatedAt.slice(0, 10)}.csv`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

function Expiry({ date, status }: { date: string | null; status: string }) {
  return (
    <span className="flex flex-wrap items-center gap-2 whitespace-nowrap tabular-nums">
      {date ?? "—"}
      <StatusBadge status={status} />
    </span>
  );
}

export function ComplianceSection({ onGenerated }: { onGenerated: () => Promise<void> }) {
  const notify = useNotify();
  const [reason, setReason] = useState("");
  const [touched, setTouched] = useState(false);
  const [pending, setPending] = useState(false);
  const [report, setReport] = useState<ComplianceReport | null>(null);
  const reasonMissing = reason.trim().length === 0;

  async function generate(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setTouched(true);
    if (reasonMissing) return;
    setPending(true);
    try {
      const result = await api<ComplianceReport>("/api/admin/compliance-report", {
        body: { reason: reason.trim() },
      });
      setReport(result);
      notify("success", "Compliance report generated");
      track("compliance_report_generated");
      await onGenerated(); // the generation is audited — refresh the log
    } catch (err) {
      notify("error", errorMessage(err));
    } finally {
      setPending(false);
    }
  }

  return (
    <AdminSection
      id="compliance"
      title="Inspection compliance report"
      description="Instead of exporting nurses' medical documents, generate an audited report of license and TB-screening status."
    >
      <form
        onSubmit={generate}
        noValidate
        className="flex flex-col gap-3 sm:flex-row sm:items-end print:hidden"
      >
        <div className="flex-1">
          <Field
            label="Reason / inspection reference"
            htmlFor="compliance-reason"
            hint="Required. Recorded in the audit log with your name and the time."
          >
            <Input
              id="compliance-reason"
              name="reason"
              required
              maxLength={200}
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              onBlur={() => setTouched(true)}
              aria-invalid={touched && reasonMissing}
              aria-describedby={touched && reasonMissing ? "compliance-reason-error" : undefined}
              placeholder="e.g. FL AHCA survey #2026-1043"
            />
          </Field>
          {touched && reasonMissing && (
            <p id="compliance-reason-error" className="mt-1 text-xs text-danger">
              Enter a reason or inspection reference.
            </p>
          )}
        </div>
        <Button type="submit" disabled={pending} className="sm:mb-6">
          {pending ? "Generating…" : "Generate report"}
        </Button>
      </form>

      {report && (
        <div className="mt-6 space-y-4">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <p className="text-sm">
              Generated by <span className="font-medium">{report.generatedBy}</span> at{" "}
              <time dateTime={report.generatedAt} className="font-medium">
                {formatDateTime(report.generatedAt)}
              </time>{" "}
              for: <span className="font-medium">{report.reason}</span>
            </p>
            <div className="flex gap-2 print:hidden">
              <Button variant="secondary" onClick={() => downloadCsv(report)}>
                Download CSV
              </Button>
              <Button variant="secondary" onClick={() => window.print()}>
                Print
              </Button>
            </div>
          </div>
          <TableScroll>
            <table className={tableClass}>
              <caption className="sr-only">License and TB screening status per nurse</caption>
              <thead className={theadClass}>
                <tr>
                  {COLUMNS.map((c) => (
                    <th key={c} scope="col" className={thClass}>
                      {c}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {report.nurses.map((n: ComplianceNurse) => (
                  <tr key={n.nurseId} className={trClass}>
                    <td className={tdClass}>{n.name}</td>
                    <td className={`${tdClass} font-mono text-xs`}>{n.licenseNumber ?? "—"}</td>
                    <td className={tdClass}>
                      <Expiry date={n.licenseExpiresAt} status={n.licenseStatus} />
                    </td>
                    <td className={tdClass}>
                      <Expiry date={n.tbScreeningExpiresAt} status={n.tbStatus} />
                    </td>
                    <td className={tdClass}>
                      {n.eligibleToday ? (
                        <span className="font-semibold text-success">
                          <span aria-hidden="true">✓</span> Yes
                        </span>
                      ) : (
                        <span className="font-semibold text-danger">
                          <span aria-hidden="true">✗</span> No
                        </span>
                      )}
                    </td>
                  </tr>
                ))}
                {report.nurses.length === 0 && (
                  <tr>
                    <td
                      colSpan={COLUMNS.length}
                      className="px-4 py-8 text-center text-sm text-muted"
                    >
                      No nurses in this report.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </TableScroll>
        </div>
      )}
    </AdminSection>
  );
}
